/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CoordinatorRouteImport } from './routes/coordinator'
import { Route as DeanRouteImport } from './routes/dean'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SupervisorRouteImport } from './routes/supervisor'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSectionRouteImport } from './routes/admin.$section'
import { Route as CoordinatorIndexRouteImport } from './routes/coordinator.index'
import { Route as CoordinatorSectionRouteImport } from './routes/coordinator.$section'
import { Route as DeanIndexRouteImport } from './routes/dean.index'
import { Route as DeanSectionRouteImport } from './routes/dean.$section'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentSectionRouteImport } from './routes/student.$section'
import { Route as SupervisorIndexRouteImport } from './routes/supervisor.index'
import { Route as SupervisorSectionRouteImport } from './routes/supervisor.$section'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinatorRoute = CoordinatorRouteImport.update({
  id: '/coordinator',
  path: '/coordinator',
  getParentRoute: () => rootRouteImport,
} as any)
const DeanRoute = DeanRouteImport.update({
  id: '/dean',
  path: '/dean',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorRoute = SupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSectionRoute = AdminSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AdminRoute,
} as any)
const CoordinatorIndexRoute = CoordinatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoordinatorRoute,
} as any)
const CoordinatorSectionRoute = CoordinatorSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => CoordinatorRoute,
} as any)
const DeanIndexRoute = DeanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeanRoute,
} as any)
const DeanSectionRoute = DeanSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => DeanRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSectionRoute = StudentSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => StudentRoute,
} as any)
const SupervisorIndexRoute = SupervisorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupervisorRoute,
} as any)
const SupervisorSectionRoute = SupervisorSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => SupervisorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/coordinator': typeof CoordinatorRouteWithChildren
  '/dean': typeof DeanRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/supervisor': typeof SupervisorRouteWithChildren
  '/admin/$section': typeof AdminSectionRoute
  '/coordinator/$section': typeof CoordinatorSectionRoute
  '/dean/$section': typeof DeanSectionRoute
  '/student/$section': typeof StudentSectionRoute
  '/supervisor/$section': typeof SupervisorSectionRoute
  '/admin/': typeof AdminIndexRoute
  '/coordinator/': typeof CoordinatorIndexRoute
  '/dean/': typeof DeanIndexRoute
  '/student/': typeof StudentIndexRoute
  '/supervisor/': typeof SupervisorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/$section': typeof AdminSectionRoute
  '/coordinator/$section': typeof CoordinatorSectionRoute
  '/dean/$section': typeof DeanSectionRoute
  '/student/$section': typeof StudentSectionRoute
  '/supervisor/$section': typeof SupervisorSectionRoute
  '/admin': typeof AdminIndexRoute
  '/coordinator': typeof CoordinatorIndexRoute
  '/dean': typeof DeanIndexRoute
  '/student': typeof StudentIndexRoute
  '/supervisor': typeof SupervisorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/coordinator': typeof CoordinatorRouteWithChildren
  '/dean': typeof DeanRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/supervisor': typeof SupervisorRouteWithChildren
  '/admin/$section': typeof AdminSectionRoute
  '/coordinator/$section': typeof CoordinatorSectionRoute
  '/dean/$section': typeof DeanSectionRoute
  '/student/$section': typeof StudentSectionRoute
  '/supervisor/$section': typeof SupervisorSectionRoute
  '/admin/': typeof AdminIndexRoute
  '/coordinator/': typeof CoordinatorIndexRoute
  '/dean/': typeof DeanIndexRoute
  '/student/': typeof StudentIndexRoute
  '/supervisor/': typeof SupervisorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/coordinator'
    | '/dean'
    | '/student'
    | '/supervisor'
    | '/admin/$section'
    | '/coordinator/$section'
    | '/dean/$section'
    | '/student/$section'
    | '/supervisor/$section'
    | '/admin/'
    | '/coordinator/'
    | '/dean/'
    | '/student/'
    | '/supervisor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/$section'
    | '/coordinator/$section'
    | '/dean/$section'
    | '/student/$section'
    | '/supervisor/$section'
    | '/admin'
    | '/coordinator'
    | '/dean'
    | '/student'
    | '/supervisor'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/coordinator'
    | '/dean'
    | '/student'
    | '/supervisor'
    | '/admin/$section'
    | '/coordinator/$section'
    | '/dean/$section'
    | '/student/$section'
    | '/supervisor/$section'
    | '/admin/'
    | '/coordinator/'
    | '/dean/'
    | '/student/'
    | '/supervisor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CoordinatorRoute: typeof CoordinatorRouteWithChildren
  DeanRoute: typeof DeanRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  SupervisorRoute: typeof SupervisorRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinator': {
      id: '/coordinator'
      path: '/coordinator'
      fullPath: '/coordinator'
      preLoaderRoute: typeof CoordinatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dean': {
      id: '/dean'
      path: '/dean'
      fullPath: '/dean'
      preLoaderRoute: typeof DeanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor': {
      id: '/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof SupervisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$section': {
      id: '/admin/$section'
      path: '/$section'
      fullPath: '/admin/$section'
      preLoaderRoute: typeof AdminSectionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/coordinator/': {
      id: '/coordinator/'
      path: '/'
      fullPath: '/coordinator/'
      preLoaderRoute: typeof CoordinatorIndexRouteImport
      parentRoute: typeof CoordinatorRoute
    }
    '/coordinator/$section': {
      id: '/coordinator/$section'
      path: '/$section'
      fullPath: '/coordinator/$section'
      preLoaderRoute: typeof CoordinatorSectionRouteImport
      parentRoute: typeof CoordinatorRoute
    }
    '/dean/': {
      id: '/dean/'
      path: '/'
      fullPath: '/dean/'
      preLoaderRoute: typeof DeanIndexRouteImport
      parentRoute: typeof DeanRoute
    }
    '/dean/$section': {
      id: '/dean/$section'
      path: '/$section'
      fullPath: '/dean/$section'
      preLoaderRoute: typeof DeanSectionRouteImport
      parentRoute: typeof DeanRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/$section': {
      id: '/student/$section'
      path: '/$section'
      fullPath: '/student/$section'
      preLoaderRoute: typeof StudentSectionRouteImport
      parentRoute: typeof StudentRoute
    }
    '/supervisor/': {
      id: '/supervisor/'
      path: '/'
      fullPath: '/supervisor/'
      preLoaderRoute: typeof SupervisorIndexRouteImport
      parentRoute: typeof SupervisorRoute
    }
    '/supervisor/$section': {
      id: '/supervisor/$section'
      path: '/$section'
      fullPath: '/supervisor/$section'
      preLoaderRoute: typeof SupervisorSectionRouteImport
      parentRoute: typeof SupervisorRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSectionRoute: typeof AdminSectionRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSectionRoute: AdminSectionRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CoordinatorRouteChildren {
  CoordinatorSectionRoute: typeof CoordinatorSectionRoute
  CoordinatorIndexRoute: typeof CoordinatorIndexRoute
}

const CoordinatorRouteChildren: CoordinatorRouteChildren = {
  CoordinatorSectionRoute: CoordinatorSectionRoute,
  CoordinatorIndexRoute: CoordinatorIndexRoute,
}

const CoordinatorRouteWithChildren = CoordinatorRoute._addFileChildren(
  CoordinatorRouteChildren,
)

interface DeanRouteChildren {
  DeanSectionRoute: typeof DeanSectionRoute
  DeanIndexRoute: typeof DeanIndexRoute
}

const DeanRouteChildren: DeanRouteChildren = {
  DeanSectionRoute: DeanSectionRoute,
  DeanIndexRoute: DeanIndexRoute,
}

const DeanRouteWithChildren = DeanRoute._addFileChildren(DeanRouteChildren)

interface StudentRouteChildren {
  StudentSectionRoute: typeof StudentSectionRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentSectionRoute: StudentSectionRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface SupervisorRouteChildren {
  SupervisorSectionRoute: typeof SupervisorSectionRoute
  SupervisorIndexRoute: typeof SupervisorIndexRoute
}

const SupervisorRouteChildren: SupervisorRouteChildren = {
  SupervisorSectionRoute: SupervisorSectionRoute,
  SupervisorIndexRoute: SupervisorIndexRoute,
}

const SupervisorRouteWithChildren = SupervisorRoute._addFileChildren(
  SupervisorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CoordinatorRoute: CoordinatorRouteWithChildren,
  DeanRoute: DeanRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  SupervisorRoute: SupervisorRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
